### ISSUE TITLE
Participate hacktoberfest 2021 event with this repo

### ISSUE THREAD

**Issue by wafarifki** [wafarifki/JungleDevs-LandingPage#2]
you can participate hacktoberfest 2021 event with this repo..

star and fork this repo.
add your name in contributing.md
do little change..
pull request
done

**Comment by YushChaudhary** [comment]
ok assign me. Thanks

**Comment by YushChaudhary** [comment]
#4 done.

**Comment by wafarifki** [comment]
> #4 done.

thank you...

**Comment by wafarifki** [comment]
done

> so can you just assign me.

done bro

**Comment by YushChaudhary** [comment]
Thanks. bro have

**Comment by wafarifki** [comment]
> Thanks. bro have

urwell bro :)

**Comment by shivanisorte** [comment]
@wafarifki Sir, it shows this (Project not participating) on hacktoberfest's official website
![image](https://user-images.githubusercontent.com/69205415/135658719-aa1f8df3-f93a-44da-b028-20d5f71d0206.png)

**Comment by YushChaudhary** [comment]
this is about one issue for a person i think let test this wafarifki can you just close this issue and add another one?

**Comment by wafarifki** [comment]
> this is about one issue for a person i think let test this wafarifki can you just close this issue and add another one?

okay let's do it

**Comment by shivanisorte** [comment]
![image](https://user-images.githubusercontent.com/69205415/135662859-9338926b-d536-47a3-9785-86aa35656c25.png)
It's working now. Thank you sir 👍

**Comment by wafarifki** [comment]
> ![image](https://user-images.githubusercontent.com/69205415/135662859-9338926b-d536-47a3-9785-86aa35656c25.png) It's working now. Thank you sir +1

urwell bro :+1:
